### ISSUE TITLE
Better installation

### ISSUE THREAD

**Issue by didair** [dustinknopoff/TeaCode-Vim-Extension#7]
To have it compatible with any plugin manager would be absolutely 💯 . 
We should at least not write the script directly to the vimrc.

**Comment by didair** [comment]
In `master` for testing.

**Comment by didair** [comment]
Just following up on this, you left a comment saying "This line imap <C-e> <C-O>:call TeaCodeExpand()<CR> might be imap <C-e> <C-O>:call Teacode-Vim-Extension#TeaCodeExpand()<CR>" did it work OOB? @dustinknopoff

**Comment by dustinknopoff** [comment]
Yes! It worked. The second option is only if using auto bundle for dynamically importing functions.
